
import java.awt.Color;
import java.util.HashSet;
import java.util.Set;

/*
 *     CAMEROS MORAN KEVIN EDUARDO
 */

/**
 *
 * @author kevin
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
    */
    
    int contPlays=0;
    boolean vsComputador=false;
    boolean b1X=false, b2X=false, b3X=false,
            b4X=false, b5X=false, b6X=false,
            b7X=false, b8X=false, b9X=false;

    boolean b1O=false, b2O=false, b3O=false,
            b4O=false, b5O=false, b6O=false,
            b7O=false, b8O=false, b9O=false;
    
    public Tablero() {
        initComponents();
        this.setLocationRelativeTo(null);
        modoJuego();
        turnoX();
        IA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        SQ1 = new javax.swing.JButton();
        SQ2 = new javax.swing.JButton();
        SQ3 = new javax.swing.JButton();
        SQ4 = new javax.swing.JButton();
        SQ5 = new javax.swing.JButton();
        SQ6 = new javax.swing.JButton();
        SQ7 = new javax.swing.JButton();
        SQ8 = new javax.swing.JButton();
        SQ9 = new javax.swing.JButton();
        etqTitulo = new javax.swing.JLabel();
        ganador = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        etqModoJuego = new javax.swing.JLabel();
        vsPC = new javax.swing.JRadioButton();
        vsAmigo = new javax.swing.JRadioButton();
        etqTurno = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jDialog1.setTitle("Aviso");
        jDialog1.setAlwaysOnTop(true);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jDialog1.getAccessibleContext().setAccessibleDescription("Vuelva pronto, aun no está desarrollado.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic-Tac-Toe");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SQ1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ1ActionPerformed(evt);
            }
        });

        SQ2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ2ActionPerformed(evt);
            }
        });

        SQ3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ3ActionPerformed(evt);
            }
        });

        SQ4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ4ActionPerformed(evt);
            }
        });

        SQ5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ5ActionPerformed(evt);
            }
        });

        SQ6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ6ActionPerformed(evt);
            }
        });

        SQ7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ7ActionPerformed(evt);
            }
        });

        SQ8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ8ActionPerformed(evt);
            }
        });

        SQ9.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        SQ9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQ9ActionPerformed(evt);
            }
        });

        etqTitulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        etqTitulo.setText("GATO");

        ganador.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        etqModoJuego.setText("Modo de juego:");

        vsPC.setText("vs computadora");
        vsPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsPCActionPerformed(evt);
            }
        });

        vsAmigo.setSelected(true);
        vsAmigo.setText("vs amigos");
        vsAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsAmigoActionPerformed(evt);
            }
        });

        etqTurno.setText("Turno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etqModoJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vsPC)
                        .addGap(18, 18, 18)
                        .addComponent(vsAmigo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SQ7, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(SQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(etqTitulo))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(SQ2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addComponent(SQ5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SQ8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SQ6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SQ9, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqModoJuego)
                    .addComponent(vsPC)
                    .addComponent(vsAmigo))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SQ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SQ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SQ6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SQ7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SQ8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SQ9, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etqTurno)
                        .addComponent(turno)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modoJuego(){
        buttonGroup1.add(vsPC);
        buttonGroup1.add(vsAmigo);
    }
    
    private void SQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ1ActionPerformed

        SQ1.setEnabled(false);
        contPlays++;
        
        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ1.setText("X");
            SQ1.setForeground(Color.red);
            b1X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ1.setText("O");
            SQ1.setForeground(Color.blue);
            b1O=true;
            turnoX();
        }
        
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();

    }//GEN-LAST:event_SQ1ActionPerformed

    private void SQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ2ActionPerformed

        SQ2.setEnabled(false);
        contPlays++;

        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ2.setText("X");
            SQ2.setForeground(Color.red);
            b2X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ2.setText("O");
            SQ2.setForeground(Color.blue);
            b2O=true;
            turnoX();
        }
        
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();
        
    }//GEN-LAST:event_SQ2ActionPerformed

    private void SQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ3ActionPerformed
        
        SQ3.setEnabled(false);
        contPlays++;
        
        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ3.setText("X");
            SQ3.setForeground(Color.red);
            b3X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ3.setText("O");
            SQ3.setForeground(Color.blue);
            b3O=true;
            turnoX();
        }
                
        if(vsComputador==true){
            IA();
        }

        Comprobaciones();
        
    }//GEN-LAST:event_SQ3ActionPerformed

    private void SQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ4ActionPerformed
        
        SQ4.setEnabled(false);
        contPlays++;

        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ4.setText("X");
            SQ4.setForeground(Color.red);
            b4X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ4.setText("O");
            SQ4.setForeground(Color.blue);
            b4O=true;
            turnoX();
        }
        
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();
        
    }//GEN-LAST:event_SQ4ActionPerformed

    private void SQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ5ActionPerformed
        
        SQ5.setEnabled(false);
        contPlays++;
        
        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ5.setText("X");
            SQ5.setForeground(Color.red);
            b5X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ5.setText("O");
            SQ5.setForeground(Color.blue);
            b5O=true;
            turnoX();
        }
        
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();
        
    }//GEN-LAST:event_SQ5ActionPerformed

    private void SQ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ6ActionPerformed
        
        SQ6.setEnabled(false);
        contPlays++;
   
        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ6.setText("X");
            SQ6.setForeground(Color.red);
            b6X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ6.setText("O");
            SQ6.setForeground(Color.blue);
            b6O=true;
            turnoX();
        }
        
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();
        
    }//GEN-LAST:event_SQ6ActionPerformed

    private void SQ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ7ActionPerformed
        
        SQ7.setEnabled(false);
        contPlays++;
        
        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ7.setText("X");
            SQ7.setForeground(Color.red);
            b7X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ7.setText("O");
            SQ7.setForeground(Color.blue);
            b7O=true;
            turnoX();
        }
        
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();
        
    }//GEN-LAST:event_SQ7ActionPerformed

    private void SQ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ8ActionPerformed
        
        SQ8.setEnabled(false);
        contPlays++;

        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ8.setText("X");
            SQ8.setForeground(Color.red);
            b8X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ8.setText("O");
            SQ8.setForeground(Color.blue);
            b8O=true;
            turnoX();
        }
                
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();
        
    }//GEN-LAST:event_SQ8ActionPerformed

    private void SQ9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQ9ActionPerformed
        
        SQ9.setEnabled(false);
        contPlays++;
  
        if(contPlays==1 || contPlays==3 || contPlays==5 || contPlays==7 ||contPlays==9){
            SQ9.setText("X");
            SQ9.setForeground(Color.red);
            b9X=true;
            turnoO();
        }else if(contPlays==2 || contPlays==4 || contPlays==6 || contPlays==8){
            SQ9.setText("O");
            SQ9.setForeground(Color.blue);
            b9O=true;
            turnoX();
        }
                
        if(vsComputador==true){
            IA();
        }
        
        Comprobaciones();
        
    }//GEN-LAST:event_SQ9ActionPerformed

    private void vsPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsPCActionPerformed
        eventoModoJuego();
        
        //METODO DE IA NO.2 / LA COMPUTADORA INICIA
        //INICIO / (VÉASE ENTRADA EN FUNCION: private void IA())
        if(contPlays==0){
            SQ1.setText("O");
            SQ1.setForeground(Color.blue);
            SQ1.setEnabled(false);
            b1O=true;
        }
        
        vsComputador=true;
    }//GEN-LAST:event_vsPCActionPerformed

    private void vsAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsAmigoActionPerformed
        eventoModoJuego();

        vsComputador=false;
    }//GEN-LAST:event_vsAmigoActionPerformed

    private void IA(){
        
        ///METODO DE IA NO.1 / EL JUGADOR INICIA
        //INICIO
        /*if(contPlays==1){
            if(b1X==true || b3X==true || b7X==true || b9X==true){
                SQ5.setText("O");
                SQ5.setEnabled(false);
                b5O=true;
            }else if(b2X==true){
                SQ9.setText("O");
                SQ9.setEnabled(false);
                b9O=true;
            }else if(b4X==true){
                SQ3.setText("O");
                SQ3.setEnabled(false);
                b3O=true;
            }else if(b6X==true){
                SQ7.setText("O");
                SQ7.setEnabled(false);
                b7O=true;
            }else if(b8X==true){
                SQ1.setText("O");
                SQ1.setEnabled(false);
                b1O=true;
            }else if(b5X==true){
                SQ1.setText("O");
                SQ1.setEnabled(false);
                b1O=true;
            }
        }else if(contPlays>=2){
            //ENTRADA
            ...
        }*/
        
        //METODO DE IA NO.2 / LA COMPUTADORA INICIA
        //(VÉASE INICIO EN FUNCION: private void vsPCActionPerformed())
        if(contPlays>=1){
            //System.out.println("Aqui el contador vale "+contPlays);
            //ENTRADA
            if(b3X==true && b1O==true && "".equals(SQ2.getText()) && "".equals(SQ4.getText()) && "".equals(SQ5.getText()) && "".equals(SQ6.getText()) && "".equals(SQ7.getText()) && "".equals(SQ8.getText()) && "".equals(SQ9.getText()) ||
               b7X==true && b1O==true && "".equals(SQ2.getText()) && "".equals(SQ3.getText()) && "".equals(SQ4.getText()) && "".equals(SQ5.getText()) && "".equals(SQ6.getText()) && "".equals(SQ8.getText()) && "".equals(SQ9.getText()) ||
               b5X==true && b1O==true && "".equals(SQ2.getText()) && "".equals(SQ3.getText()) && "".equals(SQ4.getText()) && "".equals(SQ6.getText()) && "".equals(SQ7.getText()) && "".equals(SQ8.getText()) && "".equals(SQ9.getText())){
                SQ9.setText("O");
                SQ9.setForeground(Color.blue);
                SQ9.setEnabled(false);
                b9O=true;
                //System.out.println("Aqui el contador vale "+contPlays);
            }else if(b9X==true && b1O==true && "".equals(SQ2.getText()) && "".equals(SQ3.getText()) && "".equals(SQ6.getText()) && "".equals(SQ5.getText()) && "".equals(SQ8.getText()) && "".equals(SQ7.getText()) && "".equals(SQ4.getText())){
                SQ3.setText("O");
                SQ3.setForeground(Color.blue);
                SQ3.setEnabled(false);
                b3O=true;
            }else if(b8X==true && b1O==true && "".equals(SQ2.getText()) && "".equals(SQ3.getText()) && "".equals(SQ6.getText()) && "".equals(SQ5.getText()) && "".equals(SQ9.getText()) && "".equals(SQ7.getText()) && "".equals(SQ4.getText()) ||
                     b6X==true && b1O==true && "".equals(SQ2.getText()) && "".equals(SQ3.getText()) && "".equals(SQ9.getText()) && "".equals(SQ5.getText()) && "".equals(SQ8.getText()) && "".equals(SQ7.getText()) && "".equals(SQ4.getText())){
                SQ7.setText("O");
                SQ7.setForeground(Color.blue);
                SQ7.setEnabled(false);
                b7O=true;
            }else if(b2X==true && b1O==true && "".equals(SQ6.getText()) && "".equals(SQ3.getText()) && "".equals(SQ9.getText()) && "".equals(SQ5.getText()) && "".equals(SQ8.getText()) && "".equals(SQ7.getText()) && "".equals(SQ4.getText())){
                SQ7.setText("O");
                SQ7.setForeground(Color.blue);
                SQ7.setEnabled(false);
                b7O=true;
            }else if(b4X==true && b1O==true && "".equals(SQ2.getText()) && "".equals(SQ3.getText()) && "".equals(SQ9.getText()) && "".equals(SQ5.getText()) && "".equals(SQ8.getText()) && "".equals(SQ7.getText()) && "".equals(SQ6.getText())){
                SQ3.setText("O");
                SQ3.setForeground(Color.blue);
                SQ3.setEnabled(false);
                b3O=true;
            }else if(b2X==true && b1O==true && b3O==true && "".equals(SQ9.getText())){
                SQ9.setText("O");
                SQ9.setForeground(Color.blue);
                SQ9.setEnabled(false);
                b9O=true;
            }
            
            //TERCER VUELTA
            /*if(b5X==true && b1O==true && b9O==true && b7X==true && "".equals(SQ2.getText()) && "".equals(SQ3.getText()) && "".equals(SQ6.getText()) && "".equals(SQ4.getText()) && "".equals(SQ8.getText())){
                SQ3.setText("O");
                SQ3.setForeground(Color.blue);
                SQ3.setEnabled(false);
                b3O=true;
            }else if(b5X==true && b1O==true && b9O==true && b3X==true && "".equals(SQ2.getText()) && "".equals(SQ7.getText()) && "".equals(SQ6.getText()) && "".equals(SQ4.getText()) && "".equals(SQ8.getText())){
                SQ7.setText("O");
                SQ7.setForeground(Color.blue);
                SQ7.setEnabled(false);
                b7O=true;
            }
            
            if(b1O==true && b7O==true && "".equals(SQ2.getText())){
                SQ3.setText("O");
                SQ3.setForeground(Color.blue);
                SQ3.setEnabled(false);
                b3O=true;
            }else if(b1O==true && b9O==true && "".equals(SQ2.getText())){
                SQ3.setText("O");
                SQ3.setForeground(Color.blue);
                SQ3.setEnabled(false);
                b3O=true;
            }
            if(b1O==true && b3O==true && b9X==true){
                SQ7.setText("O");
                SQ7.setForeground(Color.blue);
                SQ7.setEnabled(false);
                b7O=true;
            }*/
            
            //BLOQUEO 
            //EQUIS CENTRAL 
            //UP-DOWN
            /*
                POR COMPLETAR
            */
        }
        
    }
    
    private void Comprobaciones(){
        
        //EMPATE
            if(SQ1.isEnabled()==false &&
               SQ2.isEnabled()==false &&
               SQ3.isEnabled()==false &&
               SQ4.isEnabled()==false &&
               SQ5.isEnabled()==false &&
               SQ6.isEnabled()==false &&
               SQ7.isEnabled()==false &&
               SQ8.isEnabled()==false &&
               SQ9.isEnabled()==false){
                ganador.setText("      ¡Empate!");
                turno.setText("-");
            }
        
        if(contPlays>=5){
            if(b1X==true && b2X==true && b3X==true ||
               b4X==true && b5X==true && b6X==true ||
               b7X==true && b8X==true && b9X==true ||
                    
               b1X==true && b4X==true && b7X==true ||
               b2X==true && b5X==true && b8X==true ||
               b3X==true && b6X==true && b9X==true ||
                    
               b1X==true && b5X==true && b9X==true ||
               b3X==true && b5X==true && b7X==true ){
                ganador.setText("¡Jugador X gana!");
                turno.setText("-");
                desactivarBotones();
            }
            if(b1O==true && b2O==true && b3O==true ||
                    b4O==true && b5O==true && b6O==true ||
                    b7O==true && b8O==true && b9O==true ||
                    
                    b1O==true && b4O==true && b7O==true ||
                    b2O==true && b5O==true && b8O==true ||
                    b3O==true && b6O==true && b9O==true ||
                    
                    b1O==true && b5O==true && b9O==true ||
                    b3O==true && b5O==true && b7O==true ){
                ganador.setText("¡Jugador O gana!");
                turno.setText("-");
                desactivarBotones();
            }
        }
            
    }

    private void desactivarBotones(){
        SQ1.setEnabled(false);
        SQ2.setEnabled(false);
        SQ3.setEnabled(false);
        SQ4.setEnabled(false);
        SQ5.setEnabled(false);
        SQ6.setEnabled(false);
        SQ7.setEnabled(false);
        SQ8.setEnabled(false);
        SQ9.setEnabled(false);
    }
    
    private void eventoModoJuego(){
        contPlays=0;
        
        b1X=false;b1O=false;
        b2X=false;b2O=false;
        b3X=false;b3O=false;
        b4X=false;b4O=false;
        b5X=false;b5O=false;
        b6X=false;b6O=false;
        b7X=false;b7O=false;
        b8X=false;b8O=false;
        b9X=false;b9O=false;
        
        SQ1.setText("");SQ1.setEnabled(true);
        SQ2.setText("");SQ2.setEnabled(true);
        SQ3.setText("");SQ3.setEnabled(true);
        SQ4.setText("");SQ4.setEnabled(true);
        SQ5.setText("");SQ5.setEnabled(true);
        SQ6.setText("");SQ6.setEnabled(true);
        SQ7.setText("");SQ7.setEnabled(true);
        SQ8.setText("");SQ8.setEnabled(true);
        SQ9.setText("");SQ9.setEnabled(true);
        
        ganador.setText("");
    }
    
    private void turnoX(){
        turno.setText("X");
    }
    private void turnoO(){
        turno.setText("O");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SQ1;
    private javax.swing.JButton SQ2;
    private javax.swing.JButton SQ3;
    private javax.swing.JButton SQ4;
    private javax.swing.JButton SQ5;
    private javax.swing.JButton SQ6;
    private javax.swing.JButton SQ7;
    private javax.swing.JButton SQ8;
    private javax.swing.JButton SQ9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel etqModoJuego;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.JLabel etqTurno;
    private javax.swing.JLabel ganador;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel turno;
    private javax.swing.JRadioButton vsAmigo;
    private javax.swing.JRadioButton vsPC;
    // End of variables declaration//GEN-END:variables
}
